import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import "./globals.css";

const erick0SrobotoSlab = Roboto_Slab({
  style: "normal",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${erick0SrobotoSlab.className}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
